config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :create, :destroy]
  
  resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'foods/:date', to: 'foods#show'
  
  resources :weights, only: [:new, :create, :edit, :update, :destroy]
  
  resources :diaries, only: [:new, :create, :edit, :update, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    
      @day = Date.today
      @calorie = Food.where(meal_date: @day).where(user_id: current_user.try(:id)).sum(:kcal).round(3)
      @protein = Food.where(meal_date: @day).where(user_id: current_user.try(:id)).sum(:protein).round(3)
      @fat = Food.where(meal_date: @day).where(user_id: current_user.try(:id)).sum(:fat).round(3)
      @carbo = Food.where(meal_date: @day).where(user_id: current_user.try(:id)).sum(:carbo).round(3)
      
      @breakfasts = Food.where("meal_time = '朝食'").where(meal_date: @day).where(user_id: current_user.try(:id))
      @lunches = Food.where("meal_time = '昼食'").where(meal_date: @day).where(user_id: current_user.try(:id))
      @dinners = Food.where("meal_time = '夕食'").where(meal_date: @day).where(user_id: current_user.try(:id))
      @snacks = Food.where("meal_time = '間食'").where(meal_date: @day).where(user_id: current_user.try(:id))
      
      @weight = Weight.where(weight_date: @day).find_by(user_id: current_user.try(:id))
      
      @diary = Diary.where(diary_date: @day).find_by(user_id: current_user.try(:id))
      
  end
end

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1 class="mb-5"><%= @day.strftime("%Y年%m月%d日")%>の食事内容  </h1>
      
      <% if @weight %>
        <h2>体重<%= @weight.daily_weight %>キログラム</h2>
        <%= link_to '編集', edit_weight_path(@weight) %> 
        <%= link_to '削除', @weight, method: :delete %>
      <% else %>
        <h2>体重が記録されていません</h2>
      <% end %>
      
      <% if @diary %>
        <h2 class="mt-5">運動内容</h2>
        <p><%= @diary.content %></p>
        <%= link_to '編集', edit_diary_path(@diary) %> 
        <%= link_to '削除', @diary, method: :delete %>
      <% else %>
        <h2>運動内容が記録されていません</h2>
      <% end %>
      
      <h2 class="mt-5 mb-5">合計<%= @calorie%>キロカロリー</h2>
      <p>タンパク質<%= @protein%>グラム</p>
      <p>脂質<%= @fat%>グラム</p>
      <p class="mb-5">炭水化物<%= @carbo%>グラム</p>
      <%= link_to '食事を追加する', new_food_path, class: 'btn btn-warning w-100' %>
      <h2 class="mt-5">詳細メニュー</h2>
      
      <h3 class="mt-5">朝食</h3>
      <% @breakfasts.each do |breakfast| %>
        <p><%= breakfast.name %> <%= breakfast.kcal %>キロカロリー</p>
        <%= link_to '編集', edit_food_path(breakfast) %> 
        <%= link_to '削除', breakfast, method: :delete %>
      <% end %>
      
      <h3 class="mt-5">昼食</h3>
      <% @lunches.each do |lunch| %>
        <p><%= lunch.name %><%= lunch.kcal %>キロカロリー</p>
        <%= link_to '編集', edit_food_path(lunch) %> 
        <%= link_to '削除', lunch, method: :delete %>
      <% end %>
      
      <h3 class="mt-5">夕食</h3>
      <% @dinners.each do |dinner| %>
        <p><%= dinner.name %><%= dinner.kcal %>キロカロリー</p>
        <%= link_to '編集', edit_food_path(dinner) %> 
        <%= link_to '削除', dinner, method: :delete %>
      <% end %>
      
      <h3 class="mt-5">間食</h3>
      <% @snacks.each do |snack| %>
        <p><%= snack.name %><%= snack.kcal %>キロカロリー</p>
        <%= link_to '編集', edit_food_path(snack) %> 
        <%= link_to '削除', snack, method: :delete %>
      <% end %>
    </div>
  </div>
  
<% else %>
  <div class="bg-primary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>ユーザー登録する</h1>
      <%= link_to '登録', signup_path, class: 'btn btn-lg btn-warning' %>
    </div>
  </div>
<% end %>