config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :create, :destroy]
  
  resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'foods/:date', to: 'foods#show'
  
  resources :weights, only: [:new, :create, :edit, :update, :destroy]
  
  resources :diaries, only: [:new, :create, :edit, :update, :destroy]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  
  with_options presence: true do
      validates :name, length: { maximum: 255 }
      validates :kcal, numericality: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/}
      validates :protein, numericality: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/}
      validates :fat, numericality: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/}
      validates :carbo, numericality: true, format: { with: /\A[-]?[0-9]+(\.[0-9]+)?\z/}
      validates :meal_date
      validates :meal_time
  end
  
  def start_time
    self.meal_date 
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @foods = Food.all
  end
  
  def new
    @food = Food.new
    @past_food = Food.select(:name,:kcal,:protein,:fat,:carbo).where(user_id: current_user.try(:id)).distinct
  end

  def create
    @food = current_user.foods.build(food_params)
    @past_food = Food.select(:name,:kcal,:protein,:fat,:carbo).where(user_id: current_user.try(:id)).distinct
    
    if @food.save
      flash[:success] = '食事を記録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '食事の記録に失敗しました。'
      render :new
    end
  end
  
  def show
    @day_params = params[:date]
    @day_calorie = Food.where(meal_date: @day_params).where(user_id: current_user.try(:id)).sum(:kcal).round(3)
    @day_protein = Food.where(meal_date: @day_params).where(user_id: current_user.try(:id)).sum(:protein).round(3)
    @day_fat = Food.where(meal_date: @day_params).where(user_id: current_user.try(:id)).sum(:fat).round(3)
    @day_carbo = Food.where(meal_date: @day_params).where(user_id: current_user.try(:id)).sum(:carbo).round(3)
    
    @day_breakfasts = Food.where("meal_time = '朝食'").where(meal_date: @day_params).where(user_id: current_user.try(:id))
    @day_lunches = Food.where("meal_time = '昼食'").where(meal_date: @day_params).where(user_id: current_user.try(:id))
    @day_dinners = Food.where("meal_time = '夕食'").where(meal_date: @day_params).where(user_id: current_user.try(:id))
    @day_snacks = Food.where("meal_time = '間食'").where(meal_date: @day_params).where(user_id: current_user.try(:id))
    
    @day_weights = Weight.where(weight_date: @day_params).where(user_id: current_user.try(:id))
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    
    if @food.update(food_params)
      flash[:success] = '食事が正常に更新されました'
      redirect_to("/")
    else
      flash.now[:danger] = '食事は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @food.destroy
    flash[:success] = '食事を削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def food_params
    params.require(:food).permit(:name,:kcal,:protein,:fat,:carbo,:meal_date,:meal_time)
  end

  def correct_user
    @food = current_user.foods.find_by(id: params[:id])
    unless @food
      redirect_to root_url
    end
  end
end

app/views/foods/edit.html.erb
<%= form_with(model: @food )do |f| %>
    <div class="mb-3">
        <div class="mb-3">
        　<%= f.label :meal_date, '日付' %>
          <%= f.date_select :meal_date, {}, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :meal_time, '時間' %>
          <%= f.select :meal_time, [["朝食", "朝食"], ["昼食", "昼食"],["夕食", "夕食"],["間食", "間食"]], include_blank: "選択して下さい" %>
        </div>
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: 'form-control', rows: 5 %>
          <%= f.label :kcal, 'カロリー' %>
          <%= f.text_field :kcal, class: 'form-control', rows: 5 %>
          <%= f.label :protein, 'タンパク質' %>
          <%= f.text_field :protein, class: 'form-control', rows: 5 %>
          <%= f.label :fat, '脂質' %>
          <%= f.text_field :fat, class: 'form-control', rows: 5 %>
          <%= f.label :carbo, '炭水化物' %>
          <%= f.text_field :carbo, class: 'form-control', rows: 5 %>
    </div>
    <%= f.submit '食事を編集する', class: 'btn btn-warning w-100' %>
<% end %>

app/views/foods/index.html.erb
<%= month_calendar do |date| %>
  <%= date.day %>
  
  <% @day_calorie = Food.where(meal_date: date).where(user_id: current_user.try(:id)).sum(:kcal).round(3) %>
  <% @day_weights = Weight.where(weight_date: date).where(user_id: current_user.try(:id)).sum(:daily_weight) %>
  <% if @day_calorie != 0 %>
    総カロリー：<%= link_to @day_calorie, food_path(date) %> kcal
  <% end %>
  <% if @day_weights != 0 %>
    <p>体重 : <%= @day_weights %>キログラム</p>
  <% end %>
  
<% end %>

app/views/foods/new.html.erb
<%= form_with(model: @food )do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="mb-3">
        <div class="mb-3 text-left>
        　<%= f.label :meal_date_1i, '日付' %>
          <%= f.date_select :meal_date %>
        </div>
        <div class="mb-3">
          <%= f.label :meal_time, '時間' %>
          <%= f.select :meal_time, [["朝食", "朝食"], ["昼食", "昼食"],["夕食", "夕食"],["間食", "間食"]], include_blank: "選択して下さい" %>
        </div>

          <%= f.label :name, '名前'%>
          <%= f.text_field :name, class: 'form-control'%>
          <%= f.label :kcal, 'カロリー' %>
          <%= f.text_field :kcal, class: 'form-control'%>
          <%= f.label :protein, 'タンパク質' %>
          <%= f.text_field :protein, class: 'form-control' %>
          <%= f.label :fat, '脂質' %>
          <%= f.text_field :fat, class: 'form-control'%>
          <%= f.label :carbo, '炭水化物' %>
          <%= f.text_field :carbo, class: 'form-control'%>
    </div>
    <%= f.submit '食事を追加する', class: 'btn btn-warning w-100' %>
    
    
        <div class="mt-5 mb-3"><label>過去の食事から選ぶ</label></div>
        
        <select multiple id="select_past_food" onChange='auto_input()'>

          <% @past_food.each do |food| %>
            <option><%= food.name %>,<%= food.kcal %>,<%= food.protein %>,<%= food.fat %>,<%= food.carbo %></option>
          <% end %>
       
        </select>
    
<% end %>

<script>
  var auto_input = function () {
    var element = document.getElementById("select_past_food");
    document.getElementById("food_name").value = element.value.split(",")[0];
    document.getElementById("food_kcal").value = element.value.split(",")[1];
    document.getElementById("food_protein").value = element.value.split(",")[2];
    document.getElementById("food_fat").value = element.value.split(",")[3];
    document.getElementById("food_carbo").value = element.value.split(",")[4];
  }
</script>

app/views/foods/show.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <h1 class="mb-5"><%= @day_params %>日の食事内容</h1>
    
    <% @day_weights.each do |weight| %>
        <h2>体重<%= weight.daily_weight %>キログラム</h2>
        <%= link_to '編集', edit_weight_path(weight) %> 
        <%= link_to '削除', weight, method: :delete %>
      <% end %>
    
    <h2 class="mt-5 mb-5">合計<%= @day_calorie %>キロカロリー</h2>
    <p>タンパク質<%= @day_protein%>グラム</p>
    <p>脂質<%= @day_fat%>グラム</p>
    <p class="mb-5">炭水化物<%= @day_carbo%>グラム</p>
    <%= link_to '食事を追加する', new_food_path %>
    <h2 class="mt-5">詳細メニュー</h2>
    
    <h3 class="mt-5">朝食</h3>
    <% @day_breakfasts.each do |breakfast| %>
      <p><%= breakfast.name %></p>
      <p><%= breakfast.kcal %>キロカロリー</p>
      <%= link_to '編集', edit_food_path(breakfast) %> 
      <%= link_to '削除', breakfast, method: :delete %>
    <% end %>
    
    <h3 class="mt-5">昼食</h3>
    <% @day_lunches.each do |lunch| %>
      <p><%= lunch.name %></p>
      <p><%= lunch.kcal %>キロカロリー</p>
      <%= link_to '編集', edit_food_path(lunch) %> 
      <%= link_to '削除', lunch, method: :delete %>
    <% end %>
    
    <h3 class="mt-5">夕食</h3>
    <% @day_dinners.each do |dinner| %>
      <p><%= dinner.name %></p>
      <p><%= dinner.kcal %>キロカロリー</p>
      <%= link_to '編集', edit_food_path(dinner) %> 
      <%= link_to '削除', dinner, method: :delete %>
    <% end %>
    
    <h3 class="mt-5">間食</h3>
    <% @day_snacks.each do |snack| %>
      <p><%= snack.name %></p>
      <p><%= snack.kcal %>キロカロリー</p>
      <%= link_to '編集', edit_food_path(snack) %> 
      <%= link_to '削除', snack, method: :delete %>
    <% end %>
  </div>
</div>