config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :create, :destroy]
  
  resources :foods, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'foods/:date', to: 'foods#show'
  
  resources :weights, only: [:new, :create, :edit, :update, :destroy]
  
  resources :diaries, only: [:new, :create, :edit, :update, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Food Diary</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to '食事を追加', new_food_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '体重を記録', new_weight_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '運動内容を記録', new_diary_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'カレンダー', foods_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '退会する', current_user, data: { confirm: '退会してよいですか？' }, method: :delete, class: 'nav-link' %></li>
            <% if current_user == @user || current_user.admin? %>
              <li class="nav-item"><%= link_to '管理者ページ', users_path, class: 'nav-link' %></li>
            <% end %>
          </ul>  
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>